import re
import sqlite3

from .helper_common import (
    externalize_data_uri_images,
    extract_pptx_slides,
    get_interactive_learning_files,
    normalize_question_bank_group_text,
    normalize_relative_path,
    parse_module_names,
    pptx_to_content_slide_html,
    resolve_interactive_learning_path,
    safe_int,
)
from .helper_communication import (
    add_communication_message,
    create_communication_thread,
    get_student_message_threads,
    get_student_unread_message_count,
    get_teacher_quick_action_catalog,
    get_teacher_selected_quick_actions,
    get_teacher_unread_message_count,
    mark_student_threads_read,
    student_has_fresh_teacher_reply,
)
from .helper_attendance import (
    add_learner_note_entry,
    attendance_status_counts_as_present,
    auto_exclude_empty_attendance_days,
    build_attendance_group_summary,
    build_attendance_history,
    build_attendance_months,
    calculate_attendance_percentage,
    fetch_attendance_override_statuses,
    fetch_first_login_times,
    fetch_group_excluded_dates,
    fetch_group_late_thresholds,
    get_active_term_range,
    get_attendance_data,
    get_current_year_attendance_days,
    get_days_in_active_term,
    get_group_late_threshold,
    get_last_21_days,
    get_last_7_days,
    get_low_attendance_learners,
    get_low_attendance_learners_filtered,
    get_term_dates,
    summarize_attendance_history,
    is_attendance_editable,
)
from .helper_marking import get_marking_scripts, mark_file
from .helper_results import (
    fetch_group_practical_averages,
    fetch_group_theory_averages,
    fetch_student_practical_averages,
    fetch_student_theory_averages,
    fetch_theory_module_weaknesses,
)
from .helper_theory import (
    bank_question_exists,
    build_bank_option_signature,
    build_match_review_rows,
    clone_bank_question_to_test,
    compute_theory_answer_award,
    create_generated_match_question,
    get_fill_in_accepted_answers,
    get_question_bank_counts,
    get_true_false_option_data,
    merge_bank_match_rows_into_test,
    normalize_review_text,
    parse_true_false_answer_text,
    pick_unique_bank_question_ids,
    regrade_theory_question_answers,
    score_fill_in_answer,
    score_true_false_answer,
)
